In [2]:
import pandas as pd

employees = pd.DataFrame({
    "EmpID": [1, 2, 3, 4],
    "Name": ["Rahul", "Priya", "Amit", "Sneha"],
    "DeptID": [101, 102, 101, 104]
})

departments = pd.DataFrame({
    "DeptID": [101, 102, 103],
    "Department": ["IT", "HR", "Finance"]
})

In [3]:
employees

   EmpID   Name  DeptID
0      1  Rahul     101
1      2  Priya     102
2      3   Amit     101
3      4  Sneha     104

In [4]:
departments

   DeptID Department
0     101         IT
1     102         HR
2     103    Finance

In [7]:
result = pd.merge(
    employees,
    departments,
    on="DeptID",
    how="inner"
)

result

   EmpID   Name  DeptID Department
0      1  Rahul     101         IT
1      2  Priya     102         HR
2      3   Amit     101         IT

In [8]:
result = pd.merge(
    employees,
    departments,
    on="DeptID",
    how="left"
)

result

   EmpID   Name  DeptID Department
0      1  Rahul     101         IT
1      2  Priya     102         HR
2      3   Amit     101         IT
3      4  Sneha     104        NaN

In [9]:
result = pd.merge(
    employees,
    departments,
    on="DeptID",
    how="right"
)

result

   EmpID   Name  DeptID Department
0    1.0  Rahul     101         IT
1    3.0   Amit     101         IT
2    2.0  Priya     102         HR
3    NaN    NaN     103    Finance

In [10]:
result = pd.merge(
    employees,
    departments,
    on="DeptID",
    how="outer"
)
result

   EmpID   Name  DeptID Department
0    1.0  Rahul     101         IT
1    3.0   Amit     101         IT
2    2.0  Priya     102         HR
3    NaN    NaN     103    Finance
4    4.0  Sneha     104        NaN