In [55]:
import pandas as pd
df = pd.read_csv("output.csv")

In [56]:
# we can fill this value 
# we can drop the data point 
df

    Names  Marks
0   Rohit   90.0
1  Soumit   88.0
2  Murgan   92.0
3   Sunil   78.0
4   Varun   99.0
5   Rohit    NaN

In [57]:
# True if value is null
# False if value is not null
df.isnull()

   Names  Marks
0  False  False
1  False  False
2  False  False
3  False  False
4  False  False
5  False   True

In [58]:
df.isnull().sum()

Names    0
Marks    1
dtype: int64

In [59]:
# it will drop all the null values
df1 = df.dropna()
# inplace = True will change the df permenantlty

In [61]:
df1

    Names  Marks
0   Rohit   90.0
1  Soumit   88.0
2  Murgan   92.0
3   Sunil   78.0
4   Varun   99.0

In [54]:
df

    Names  Marks
0   Rohit   90.0
1  Soumit   88.0
2  Murgan   92.0
3   Sunil   78.0
4   Varun   99.0
5   Rohit    NaN

In [62]:
df.dropna(inplace = True)

In [63]:
df

    Names  Marks
0   Rohit   90.0
1  Soumit   88.0
2  Murgan   92.0
3   Sunil   78.0
4   Varun   99.0

In [66]:
# drop duplicate
# used for dropping the duplicate values 
df.drop_duplicates(inplace = True)
df

    Names  Marks
0   Rohit   90.0
1  Soumit   88.0
2  Murgan   92.0
3   Sunil   78.0
4   Varun   99.0

In [67]:
# drop column
# used to drop any column from your dataset 
df.drop(["Names"] , axis=1)
# names column is gone and only marks column is there

   Marks
0   90.0
1   88.0
2   92.0
3   78.0
4   99.0

In [69]:
# drop 2 columns 
# how can you drop
df.drop(["Names" , "Marks"] , axis = 1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [70]:
df

    Names  Marks
0   Rohit   90.0
1  Soumit   88.0
2  Murgan   92.0
3   Sunil   78.0
4   Varun   99.0

In [73]:
# how to rename the column
df.rename({"Names":"Students"} , axis = 1)

  Students  Marks
0    Rohit   90.0
1   Soumit   88.0
2   Murgan   92.0
3    Sunil   78.0
4    Varun   99.0

In [74]:
# how to fill the null values 
# mean median mode

# mean is the average of all the datapoints (numerical)
# median is the centeral value (middle value)
    # if you have even numbers of records then sorted(n/2 , n+2/2)/2 this become your mean
    # this is the mean (n/2 , n+2/2)/2
    # if number of records are odd then (n/2 + 1) th record will be your median

# mode is the most repeated value in your [column] 
# ["Rohit" , "Rohit" , "Rohit" , "Varun" , "Soumit"] --> from this data "Rohit" will be your mode

# Assignment: Handling Missing Values Using Mean, Median, and Mode

## Objective
Understand the mathematical calculation of Mean, Median, and Mode to fill missing values in a dataset.

### 1. Mean (Average)

The ages of five students are:

`20, 22, 24, 26, NaN`

**Tasks:**
1. Calculate the mean of the available ages.
2. Replace the missing value (`NaN`) with the calculated mean.
3. Write the final list of ages.

**Formula:**

Mean = Sum of all values / Number of values

### 2. Median (Middle Value)

The salaries of five employees are:

`15000, 20000, 25000, 30000, NaN`

**Tasks:**
1. Arrange the available salaries in ascending order.
2. Find the median salary.
3. Replace the missing value (`NaN`) with the calculated median.
4. Write the final list of salaries.

**Hint:** If the number of values is even, the median is the average of the two middle values.

### 3. Mode (Most Frequent Value)

The departments of employees are:

`IT, HR, IT, Sales, IT, HR, NaN`

**Tasks:**
1. Count the frequency of each department.
2. Identify the mode.
3. Replace the missing value (`NaN`) with the mode.
4. Write the final list of departments.

### 4. Bonus Questions

1. Calculate the mean of `10, 20, 30, 40, 50`.
2. Find the median of `12, 8, 15, 10, 20, 25`.
3. Find the median of `5, 10, 15, 20, 25`.
4. Find the mode of `2, 3, 3, 4, 5, 3, 6`.
5. If a dataset contains an extremely high salary, which is generally more suitable for filling a missing salary: Mean or Median? Explain why.

**Instructions:** Solve all questions using mathematical calculations only. Do not use Python, Pandas, or any built-in functions.

In [ ]:
# will see how to find the mean median and mode of the data