In [1]:
# we will start on pandas

In [2]:
# how to load csv , excel files 
# how to load the data from the dictionary

In [32]:
students = {
    "Names":["Rohit" , "Soumit" , "Murgan" , "Sunil" , "Varun" , "Rohit"] , "Marks":[90 , 88 , 92 , 78 , 99 , N ]
}

In [33]:
import pandas as pd
df = pd.DataFrame(students)

In [34]:
df

    Names  Marks
0   Rohit   90.0
1  Soumit   88.0
2  Murgan   92.0
3   Sunil   78.0
4   Varun   99.0
5   Rohit    NaN

In [13]:
df.to_csv("output.csv")
# to save the dataframe into the csv file

In [15]:
df.to_excel("output.xlsx")
# to save the dataframe into the excel file

In [17]:
# how to see the top 5 records of the dataframe 
df.head()

    Names  Marks
0   Rohit   90.0
1  Soumit   88.0
2  Murgan   92.0
3   Sunil   78.0
4   Varun   99.0

In [18]:
# for top 3 records
df.head(3)

    Names  Marks
0   Rohit   90.0
1  Soumit   88.0
2  Murgan   92.0

In [35]:
# if i want to see the bottom 5 rows 
df.tail()

    Names  Marks
1  Soumit   88.0
2  Murgan   92.0
3   Sunil   78.0
4   Varun   99.0
5   Rohit    NaN

In [36]:
# if i want to see the bottom 2 rows 
df.tail(2)

   Names  Marks
4  Varun   99.0
5  Rohit    NaN

In [37]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Names   6 non-null      str
 1   Marks   5 non-null      float64
dtypes: float64(1), str(1)
memory usage: 260.0 bytes

In [38]:
# only for the numerical columns
df.describe()

           Marks
count   5.000000
mean   89.400000
std     7.602631
min    78.000000
25%    88.000000
50%    90.000000
75%    92.000000
max    99.000000

In [29]:
# only for the categorical columns
df.describe(include=str)

        Names
count       6
unique      5
top     Rohit
freq        2

In [ ]:
# just give a little brief summary in next session about describe and include