In [3]:
import pandas as pd
df = pd.read_csv("demo_data.csv")

In [4]:
df.head()

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceRating
0,101,Rahul,IT,25,Male,45000,2,Pune,4
1,102,Priya,HR,29,Female,52000,4,Mumbai,5
2,103,Amit,IT,32,Male,75000,8,Bengaluru,4
3,104,Sneha,Finance,28,Female,60000,5,Pune,3
4,105,Vikas,HR,35,Male,48000,6,Mumbai,4

In [6]:
selected_columns = df[["EmployeeID",	"Name",	"Department",	"Age",	"Gender",	"Salary",	"Experience"]]

In [7]:
selected_columns

    EmployeeID    Name Department  Age  Gender  Salary  Experience
0          101   Rahul         IT   25    Male   45000           2
1          102   Priya         HR   29  Female   52000           4
2          103    Amit         IT   32    Male   75000           8
3          104   Sneha    Finance   28  Female   60000           5
4          105   Vikas         HR   35    Male   48000           6
5          106    Neha         IT   27  Female   65000           3
6          107   Rohit    Finance   40    Male   85000          12
7          108   Pooja         IT   30  Female   70000           7
8          109   Karan      Sales   26    Male   40000           1
9          110  Anjali         HR   31  Female   55000           5
10         111  Suresh      Sales   38    Male   62000           9
11         112   Meera    Finance   33  Female   72000           8
12         113   Akash         IT   24    Male   42000           1
13         114    Riya      Sales   29  Female   50000           3
14         115  Nikhil    Finance   36    Male   80000          10

In [11]:
one_column = df[["EmployeeID"]]
type(one_column)

pandas.DataFrame

In [18]:
one_column = df["EmployeeID"]
type(one_column)

# series object
# series is the single column is called as the series

pandas.Series

In [21]:
df1 = df[["EmployeeID",	"Name"]]
df1

    EmployeeID    Name
0          101   Rahul
1          102   Priya
2          103    Amit
3          104   Sneha
4          105   Vikas
5          106    Neha
6          107   Rohit
7          108   Pooja
8          109   Karan
9          110  Anjali
10         111  Suresh
11         112   Meera
12         113   Akash
13         114    Riya
14         115  Nikhil

In [22]:
df.columns

Index(['EmployeeID', 'Name', 'Department', 'Age', 'Gender', 'Salary',
       'Experience', 'City', 'PerformanceRating'],
      dtype='str')

In [24]:
# only 8 columns i want to select
df2 = df.drop(["PerformanceRating"] , axis = 1)

In [25]:
df2

    EmployeeID    Name Department  Age  Gender  Salary  Experience       City
0          101   Rahul         IT   25    Male   45000           2       Pune
1          102   Priya         HR   29  Female   52000           4     Mumbai
2          103    Amit         IT   32    Male   75000           8  Bengaluru
3          104   Sneha    Finance   28  Female   60000           5       Pune
4          105   Vikas         HR   35    Male   48000           6     Mumbai
5          106    Neha         IT   27  Female   65000           3  Bengaluru
6          107   Rohit    Finance   40    Male   85000          12       Pune
7          108   Pooja         IT   30  Female   70000           7     Mumbai
8          109   Karan      Sales   26    Male   40000           1       Pune
9          110  Anjali         HR   31  Female   55000           5  Bengaluru
10         111  Suresh      Sales   38    Male   62000           9     Mumbai
11         112   Meera    Finance   33  Female   72000           8       Pune
12         113   Akash         IT   24    Male   42000           1  Bengaluru
13         114    Riya      Sales   29  Female   50000           3     Mumbai
14         115  Nikhil    Finance   36    Male   80000          10       Pune

In [26]:
df2 = df.drop(["EmployeeID",	"Name"] , axis = 1)

In [27]:
df2

   Department  Age  Gender  Salary  Experience       City  PerformanceRating
0          IT   25    Male   45000           2       Pune                  4
1          HR   29  Female   52000           4     Mumbai                  5
2          IT   32    Male   75000           8  Bengaluru                  4
3     Finance   28  Female   60000           5       Pune                  3
4          HR   35    Male   48000           6     Mumbai                  4
5          IT   27  Female   65000           3  Bengaluru                  5
6     Finance   40    Male   85000          12       Pune                  3
7          IT   30  Female   70000           7     Mumbai                  4
8       Sales   26    Male   40000           1       Pune                  3
9          HR   31  Female   55000           5  Bengaluru                  4
10      Sales   38    Male   62000           9     Mumbai                  5
11    Finance   33  Female   72000           8       Pune                  4
12         IT   24    Male   42000           1  Bengaluru                  3
13      Sales   29  Female   50000           3     Mumbai                  4
14    Finance   36    Male   80000          10       Pune                  5

In [28]:
# df.iloc
# what is iloc ?
# iloc is used to slice the rows from the dataframe

In [34]:
df.head()

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceRating
0,101,Rahul,IT,25,Male,45000,2,Pune,4
1,102,Priya,HR,29,Female,52000,4,Mumbai,5
2,103,Amit,IT,32,Male,75000,8,Bengaluru,4
3,104,Sneha,Finance,28,Female,60000,5,Pune,3
4,105,Vikas,HR,35,Male,48000,6,Mumbai,4

In [39]:
df.iloc[0 , 1]

'Rahul'

In [38]:
df.iloc[2 , 3]

np.int64(32)

In [40]:
df.iloc[2:7 , 1:4]

    Name Department  Age
2   Amit         IT   32
3  Sneha    Finance   28
4  Vikas         HR   35
5   Neha         IT   27
6  Rohit    Finance   40

In [41]:
df.head()

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceRating
0,101,Rahul,IT,25,Male,45000,2,Pune,4
1,102,Priya,HR,29,Female,52000,4,Mumbai,5
2,103,Amit,IT,32,Male,75000,8,Bengaluru,4
3,104,Sneha,Finance,28,Female,60000,5,Pune,3
4,105,Vikas,HR,35,Male,48000,6,Mumbai,4

In [42]:
df.iloc[0: , 1:6:2]

      Name  Age  Salary
0    Rahul   25   45000
1    Priya   29   52000
2     Amit   32   75000
3    Sneha   28   60000
4    Vikas   35   48000
5     Neha   27   65000
6    Rohit   40   85000
7    Pooja   30   70000
8    Karan   26   40000
9   Anjali   31   55000
10  Suresh   38   62000
11   Meera   33   72000
12   Akash   24   42000
13    Riya   29   50000
14  Nikhil   36   80000

In [47]:
df.iloc[[2,3,4,5,10] , [1 , 3 , 7]]

# df.iloc[row indexes , column index]

      Name  Age       City
2     Amit   32  Bengaluru
3    Sneha   28       Pune
4    Vikas   35     Mumbai
5     Neha   27  Bengaluru
10  Suresh   38     Mumbai

In [48]:
# please practise iloc

In [49]:
df

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceRating
0,101,Rahul,IT,25,Male,45000,2,Pune,4
1,102,Priya,HR,29,Female,52000,4,Mumbai,5
2,103,Amit,IT,32,Male,75000,8,Bengaluru,4
3,104,Sneha,Finance,28,Female,60000,5,Pune,3
4,105,Vikas,HR,35,Male,48000,6,Mumbai,4
5,106,Neha,IT,27,Female,65000,3,Bengaluru,5
6,107,Rohit,Finance,40,Male,85000,12,Pune,3
7,108,Pooja,IT,30,Female,70000,7,Mumbai,4
8,109,Karan,Sales,26,Male,40000,1,Pune,3
9,110,Anjali,HR,31,Female,55000,5,Bengaluru,4
10,111,Suresh,Sales,38,Male,62000,9,Mumbai,5
11,112,Meera,Finance,33,Female,72000,8,Pune,4
12,113,Akash,IT,24,Male,42000,1,Bengaluru,3
13,114,Riya,Sales,29,Female,50000,3,Mumbai,4
14,115,Nikhil,Finance,36,Male,80000,10,Pune,5

In [58]:
df.loc[0:10 , ["EmployeeID"]]

    EmployeeID
0          101
1          102
2          103
3          104
4          105
5          106
6          107
7          108
8          109
9          110
10         111

In [63]:
df.loc[1:10 , ["EmployeeID" , "Experience"]]

    EmployeeID  Experience
1          102           4
2          103           8
3          104           5
4          105           6
5          106           3
6          107          12
7          108           7
8          109           1
9          110           5
10         111           9

In [ ]:
df.loc[[1,4,5,6,7] , ["EmployeeID" , "Experience"]]

In [64]:
# client said process the top 1000 rows on Name		Age		Salary	 Experience
df.loc[0:1000 , ["Name",	"Age","Salary",	"Experience"]]

      Name  Age  Salary  Experience
0    Rahul   25   45000           2
1    Priya   29   52000           4
2     Amit   32   75000           8
3    Sneha   28   60000           5
4    Vikas   35   48000           6
5     Neha   27   65000           3
6    Rohit   40   85000          12
7    Pooja   30   70000           7
8    Karan   26   40000           1
9   Anjali   31   55000           5
10  Suresh   38   62000           9
11   Meera   33   72000           8
12   Akash   24   42000           1
13    Riya   29   50000           3
14  Nikhil   36   80000          10

In [66]:
df.iloc[3:10:2 ,2:8]

  Department  Age  Gender  Salary  Experience       City
3    Finance   28  Female   60000           5       Pune
5         IT   27  Female   65000           3  Bengaluru
7         IT   30  Female   70000           7     Mumbai
9         HR   31  Female   55000           5  Bengaluru