In [1]:
import pandas as pd

data = {
    "EmployeeID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                   111, 112, 113, 114, 115],
    "Name": ["Rahul", "Priya", "Amit", "Sneha", "Vikas",
             "Neha", "Rohit", "Pooja", "Karan", "Anjali",
             "Suresh", "Meera", "Akash", "Riya", "Nikhil"],
    "Department": ["IT", "HR", "IT", "Finance", "HR",
                   "IT", "Finance", "IT", "Sales", "HR",
                   "Sales", "Finance", "IT", "Sales", "Finance"],
    "Age": [25, 29, 32, 28, 35, 27, 40, 30, 26, 31,
            38, 33, 24, 29, 36],
    "Gender": ["Male", "Female", "Male", "Female", "Male",
               "Female", "Male", "Female", "Male", "Female",
               "Male", "Female", "Male", "Female", "Male"],
    "Salary": [45000, 52000, 75000, 60000, 48000,
               65000, 85000, 70000, 40000, 55000,
               62000, 72000, 42000, 50000, 80000],
    "Experience": [2, 4, 8, 5, 6, 3, 12, 7, 1, 5,
                   9, 8, 1, 3, 10],
    "City": ["Pune", "Mumbai", "Bengaluru", "Pune", "Mumbai",
             "Bengaluru", "Pune", "Mumbai", "Pune", "Bengaluru",
             "Mumbai", "Pune", "Bengaluru", "Mumbai", "Pune"],
    "PerformanceRating": [4, 5, 4, 3, 4, 5, 3, 4, 3, 4,
                          5, 4, 3, 4, 5]
}

df = pd.DataFrame(data)
df

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceRating
0,101,Rahul,IT,25,Male,45000,2,Pune,4
1,102,Priya,HR,29,Female,52000,4,Mumbai,5
2,103,Amit,IT,32,Male,75000,8,Bengaluru,4
3,104,Sneha,Finance,28,Female,60000,5,Pune,3
4,105,Vikas,HR,35,Male,48000,6,Mumbai,4
5,106,Neha,IT,27,Female,65000,3,Bengaluru,5
6,107,Rohit,Finance,40,Male,85000,12,Pune,3
7,108,Pooja,IT,30,Female,70000,7,Mumbai,4
8,109,Karan,Sales,26,Male,40000,1,Pune,3
9,110,Anjali,HR,31,Female,55000,5,Bengaluru,4
10,111,Suresh,Sales,38,Male,62000,9,Mumbai,5
11,112,Meera,Finance,33,Female,72000,8,Pune,4
12,113,Akash,IT,24,Male,42000,1,Bengaluru,3
13,114,Riya,Sales,29,Female,50000,3,Mumbai,4
14,115,Nikhil,Finance,36,Male,80000,10,Pune,5

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   EmployeeID         15 non-null     int64
 1   Name               15 non-null     str
 2   Department         15 non-null     str
 3   Age                15 non-null     int64
 4   Gender             15 non-null     str
 5   Salary             15 non-null     int64
 6   Experience         15 non-null     int64
 7   City               15 non-null     str
 8   PerformanceRating  15 non-null     int64
dtypes: int64(5), str(4)
memory usage: 1.5 KB

In [3]:
df.describe()

       EmployeeID        Age        Salary  Experience  PerformanceRating
count   15.000000  15.000000     15.000000   15.000000          15.000000
mean   108.000000  30.866667  60066.666667    5.600000           4.000000
std      4.472136   4.778922  14154.588689    3.355167           0.755929
min    101.000000  24.000000  40000.000000    1.000000           3.000000
25%    104.500000  27.500000  49000.000000    3.000000           3.500000
50%    108.000000  30.000000  60000.000000    5.000000           4.000000
75%    111.500000  34.000000  71000.000000    8.000000           4.500000
max    115.000000  40.000000  85000.000000   12.000000           5.000000

In [4]:
df.isnull().sum()

EmployeeID           0
Name                 0
Department           0
Age                  0
Gender               0
Salary               0
Experience           0
City                 0
PerformanceRating    0
dtype: int64

In [9]:
df1 = df.dropna()
df1

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceRating
0,101,Rahul,IT,25,Male,45000,2,Pune,4
1,102,Priya,HR,29,Female,52000,4,Mumbai,5
2,103,Amit,IT,32,Male,75000,8,Bengaluru,4
3,104,Sneha,Finance,28,Female,60000,5,Pune,3
4,105,Vikas,HR,35,Male,48000,6,Mumbai,4
5,106,Neha,IT,27,Female,65000,3,Bengaluru,5
6,107,Rohit,Finance,40,Male,85000,12,Pune,3
7,108,Pooja,IT,30,Female,70000,7,Mumbai,4
8,109,Karan,Sales,26,Male,40000,1,Pune,3
9,110,Anjali,HR,31,Female,55000,5,Bengaluru,4
10,111,Suresh,Sales,38,Male,62000,9,Mumbai,5
11,112,Meera,Finance,33,Female,72000,8,Pune,4
12,113,Akash,IT,24,Male,42000,1,Bengaluru,3
13,114,Riya,Sales,29,Female,50000,3,Mumbai,4
14,115,Nikhil,Finance,36,Male,80000,10,Pune,5

In [11]:
df1 = df1.drop_duplicates()
df1

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceRating
0,101,Rahul,IT,25,Male,45000,2,Pune,4
1,102,Priya,HR,29,Female,52000,4,Mumbai,5
2,103,Amit,IT,32,Male,75000,8,Bengaluru,4
3,104,Sneha,Finance,28,Female,60000,5,Pune,3
4,105,Vikas,HR,35,Male,48000,6,Mumbai,4
5,106,Neha,IT,27,Female,65000,3,Bengaluru,5
6,107,Rohit,Finance,40,Male,85000,12,Pune,3
7,108,Pooja,IT,30,Female,70000,7,Mumbai,4
8,109,Karan,Sales,26,Male,40000,1,Pune,3
9,110,Anjali,HR,31,Female,55000,5,Bengaluru,4
10,111,Suresh,Sales,38,Male,62000,9,Mumbai,5
11,112,Meera,Finance,33,Female,72000,8,Pune,4
12,113,Akash,IT,24,Male,42000,1,Bengaluru,3
13,114,Riya,Sales,29,Female,50000,3,Mumbai,4
14,115,Nikhil,Finance,36,Male,80000,10,Pune,5

In [12]:
# organization decides that number of performance rating that many laks will be increased in base salary 
# i willc create new column New Package

df["New Package"] = df["Salary"]*12 + df["PerformanceRating"]*100000

In [13]:
df

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceRating,New Package
0,101,Rahul,IT,25,Male,45000,2,Pune,4,940000
1,102,Priya,HR,29,Female,52000,4,Mumbai,5,1124000
2,103,Amit,IT,32,Male,75000,8,Bengaluru,4,1300000
3,104,Sneha,Finance,28,Female,60000,5,Pune,3,1020000
4,105,Vikas,HR,35,Male,48000,6,Mumbai,4,976000
5,106,Neha,IT,27,Female,65000,3,Bengaluru,5,1280000
6,107,Rohit,Finance,40,Male,85000,12,Pune,3,1320000
7,108,Pooja,IT,30,Female,70000,7,Mumbai,4,1240000
8,109,Karan,Sales,26,Male,40000,1,Pune,3,780000
9,110,Anjali,HR,31,Female,55000,5,Bengaluru,4,1060000
10,111,Suresh,Sales,38,Male,62000,9,Mumbai,5,1244000
11,112,Meera,Finance,33,Female,72000,8,Pune,4,1264000
12,113,Akash,IT,24,Male,42000,1,Bengaluru,3,804000
13,114,Riya,Sales,29,Female,50000,3,Mumbai,4,1000000
14,115,Nikhil,Finance,36,Male,80000,10,Pune,5,1460000

In [14]:
df["Old Package"] = df["Salary"] * 12

In [15]:
df

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceRating,New Package,Old Package
0,101,Rahul,IT,25,Male,45000,2,Pune,4,940000,540000
1,102,Priya,HR,29,Female,52000,4,Mumbai,5,1124000,624000
2,103,Amit,IT,32,Male,75000,8,Bengaluru,4,1300000,900000
3,104,Sneha,Finance,28,Female,60000,5,Pune,3,1020000,720000
4,105,Vikas,HR,35,Male,48000,6,Mumbai,4,976000,576000
5,106,Neha,IT,27,Female,65000,3,Bengaluru,5,1280000,780000
6,107,Rohit,Finance,40,Male,85000,12,Pune,3,1320000,1020000
7,108,Pooja,IT,30,Female,70000,7,Mumbai,4,1240000,840000
8,109,Karan,Sales,26,Male,40000,1,Pune,3,780000,480000
9,110,Anjali,HR,31,Female,55000,5,Bengaluru,4,1060000,660000
10,111,Suresh,Sales,38,Male,62000,9,Mumbai,5,1244000,744000
11,112,Meera,Finance,33,Female,72000,8,Pune,4,1264000,864000
12,113,Akash,IT,24,Male,42000,1,Bengaluru,3,804000,504000
13,114,Riya,Sales,29,Female,50000,3,Mumbai,4,1000000,600000
14,115,Nikhil,Finance,36,Male,80000,10,Pune,5,1460000,960000

In [16]:
df

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceRating,New Package,Old Package
0,101,Rahul,IT,25,Male,45000,2,Pune,4,940000,540000
1,102,Priya,HR,29,Female,52000,4,Mumbai,5,1124000,624000
2,103,Amit,IT,32,Male,75000,8,Bengaluru,4,1300000,900000
3,104,Sneha,Finance,28,Female,60000,5,Pune,3,1020000,720000
4,105,Vikas,HR,35,Male,48000,6,Mumbai,4,976000,576000
5,106,Neha,IT,27,Female,65000,3,Bengaluru,5,1280000,780000
6,107,Rohit,Finance,40,Male,85000,12,Pune,3,1320000,1020000
7,108,Pooja,IT,30,Female,70000,7,Mumbai,4,1240000,840000
8,109,Karan,Sales,26,Male,40000,1,Pune,3,780000,480000
9,110,Anjali,HR,31,Female,55000,5,Bengaluru,4,1060000,660000
10,111,Suresh,Sales,38,Male,62000,9,Mumbai,5,1244000,744000
11,112,Meera,Finance,33,Female,72000,8,Pune,4,1264000,864000
12,113,Akash,IT,24,Male,42000,1,Bengaluru,3,804000,504000
13,114,Riya,Sales,29,Female,50000,3,Mumbai,4,1000000,600000
14,115,Nikhil,Finance,36,Male,80000,10,Pune,5,1460000,960000

In [25]:
df["Column name"] = list(range(1 , 16))

In [26]:
df

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceRating,New Package,Old Package,Column name
0,101,Rahul,IT,25,Male,45000,2,Pune,4,940000,540000,1
1,102,Priya,HR,29,Female,52000,4,Mumbai,5,1124000,624000,2
2,103,Amit,IT,32,Male,75000,8,Bengaluru,4,1300000,900000,3
3,104,Sneha,Finance,28,Female,60000,5,Pune,3,1020000,720000,4
4,105,Vikas,HR,35,Male,48000,6,Mumbai,4,976000,576000,5
5,106,Neha,IT,27,Female,65000,3,Bengaluru,5,1280000,780000,6
6,107,Rohit,Finance,40,Male,85000,12,Pune,3,1320000,1020000,7
7,108,Pooja,IT,30,Female,70000,7,Mumbai,4,1240000,840000,8
8,109,Karan,Sales,26,Male,40000,1,Pune,3,780000,480000,9
9,110,Anjali,HR,31,Female,55000,5,Bengaluru,4,1060000,660000,10
10,111,Suresh,Sales,38,Male,62000,9,Mumbai,5,1244000,744000,11
11,112,Meera,Finance,33,Female,72000,8,Pune,4,1264000,864000,12
12,113,Akash,IT,24,Male,42000,1,Bengaluru,3,804000,504000,13
13,114,Riya,Sales,29,Female,50000,3,Mumbai,4,1000000,600000,14
14,115,Nikhil,Finance,36,Male,80000,10,Pune,5,1460000,960000,15

In [27]:
# again you want to do the change in existing column 
# Example: "New Package"
# multiple ways are there but for simplest thing just go with the apply method
# whats the apply method

# you just create the function which will take each record from the dataframe 
# and apply the operation on that value or 
# example company said that every emplpyees salary will be deducted by 1 lakh as the quater was very
# bad no revenue generation in this quater 

# if salary is greater than 9 lakhs then 2 lakh will be reduced and if less than 9 lakh then 1 lakh 
# reduction

In [32]:
def salary_reducer(value):
    if value >= 900000:
        return value - 200000
    else:
        return value - 100000

In [33]:
df["Salary Reduction"] = df["New Package"].apply(salary_reducer)

In [35]:
df

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceRating,New Package,Old Package,Column name,Salary Reduction
0,101,Rahul,IT,25,Male,45000,2,Pune,4,940000,540000,1,740000
1,102,Priya,HR,29,Female,52000,4,Mumbai,5,1124000,624000,2,924000
2,103,Amit,IT,32,Male,75000,8,Bengaluru,4,1300000,900000,3,1100000
3,104,Sneha,Finance,28,Female,60000,5,Pune,3,1020000,720000,4,820000
4,105,Vikas,HR,35,Male,48000,6,Mumbai,4,976000,576000,5,776000
5,106,Neha,IT,27,Female,65000,3,Bengaluru,5,1280000,780000,6,1080000
6,107,Rohit,Finance,40,Male,85000,12,Pune,3,1320000,1020000,7,1120000
7,108,Pooja,IT,30,Female,70000,7,Mumbai,4,1240000,840000,8,1040000
8,109,Karan,Sales,26,Male,40000,1,Pune,3,780000,480000,9,680000
9,110,Anjali,HR,31,Female,55000,5,Bengaluru,4,1060000,660000,10,860000
10,111,Suresh,Sales,38,Male,62000,9,Mumbai,5,1244000,744000,11,1044000
11,112,Meera,Finance,33,Female,72000,8,Pune,4,1264000,864000,12,1064000
12,113,Akash,IT,24,Male,42000,1,Bengaluru,3,804000,504000,13,704000
13,114,Riya,Sales,29,Female,50000,3,Mumbai,4,1000000,600000,14,800000
14,115,Nikhil,Finance,36,Male,80000,10,Pune,5,1460000,960000,15,1260000

In [37]:
# what will happen in ml
# you cant pass the string to model for training 
# you should have the numbers only 
# then how will we convert the string into number

In [38]:
def gender_to_number(gender):
    if gender == "Male":
        return 0
    if gender == "Female":
        return 1

In [39]:
df["Gender"] = df["Gender"].apply(gender_to_number)

In [40]:
df

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceRating,New Package,Old Package,Column name,Salary Reduction
0,101,Rahul,IT,25,0,45000,2,Pune,4,940000,540000,1,740000
1,102,Priya,HR,29,1,52000,4,Mumbai,5,1124000,624000,2,924000
2,103,Amit,IT,32,0,75000,8,Bengaluru,4,1300000,900000,3,1100000
3,104,Sneha,Finance,28,1,60000,5,Pune,3,1020000,720000,4,820000
4,105,Vikas,HR,35,0,48000,6,Mumbai,4,976000,576000,5,776000
5,106,Neha,IT,27,1,65000,3,Bengaluru,5,1280000,780000,6,1080000
6,107,Rohit,Finance,40,0,85000,12,Pune,3,1320000,1020000,7,1120000
7,108,Pooja,IT,30,1,70000,7,Mumbai,4,1240000,840000,8,1040000
8,109,Karan,Sales,26,0,40000,1,Pune,3,780000,480000,9,680000
9,110,Anjali,HR,31,1,55000,5,Bengaluru,4,1060000,660000,10,860000
10,111,Suresh,Sales,38,0,62000,9,Mumbai,5,1244000,744000,11,1044000
11,112,Meera,Finance,33,1,72000,8,Pune,4,1264000,864000,12,1064000
12,113,Akash,IT,24,0,42000,1,Bengaluru,3,804000,504000,13,704000
13,114,Riya,Sales,29,1,50000,3,Mumbai,4,1000000,600000,14,800000
14,115,Nikhil,Finance,36,0,80000,10,Pune,5,1460000,960000,15,1260000

In [43]:
# hr = 1
# finance = 2
# it = 3

def dept_to_number(dept):
    if dept == "HR":
        return 1
    elif dept == "Sales":
        return 2
    elif dept == "IT":
        return 3
    elif dept == "Finance":
        return 4
    else:
        return 5

In [44]:
df["Department"] = df["Department"].apply(dept_to_number)

In [45]:
df

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceRating,New Package,Old Package,Column name,Salary Reduction
0,101,Rahul,3,25,0,45000,2,Pune,4,940000,540000,1,740000
1,102,Priya,1,29,1,52000,4,Mumbai,5,1124000,624000,2,924000
2,103,Amit,3,32,0,75000,8,Bengaluru,4,1300000,900000,3,1100000
3,104,Sneha,4,28,1,60000,5,Pune,3,1020000,720000,4,820000
4,105,Vikas,1,35,0,48000,6,Mumbai,4,976000,576000,5,776000
5,106,Neha,3,27,1,65000,3,Bengaluru,5,1280000,780000,6,1080000
6,107,Rohit,4,40,0,85000,12,Pune,3,1320000,1020000,7,1120000
7,108,Pooja,3,30,1,70000,7,Mumbai,4,1240000,840000,8,1040000
8,109,Karan,2,26,0,40000,1,Pune,3,780000,480000,9,680000
9,110,Anjali,1,31,1,55000,5,Bengaluru,4,1060000,660000,10,860000
10,111,Suresh,2,38,0,62000,9,Mumbai,5,1244000,744000,11,1044000
11,112,Meera,4,33,1,72000,8,Pune,4,1264000,864000,12,1064000
12,113,Akash,3,24,0,42000,1,Bengaluru,3,804000,504000,13,704000
13,114,Riya,2,29,1,50000,3,Mumbai,4,1000000,600000,14,800000
14,115,Nikhil,4,36,0,80000,10,Pune,5,1460000,960000,15,1260000

In [46]:
# if i ask you to convery city into the numbers 
# how will you do it

In [49]:
location = []
for i in range(1 , 16):
    location.append("Hyderabad")
df["Location"] = location

In [ ]:
# if the new column name is matching the existing column name in dataframe
# then that existing column will be replaced by the new column

In [52]:
df

,EmployeeID,Name,Department,Age,Gender,Salary,Experience,City,PerformanceRating,New Package,Old Package,Column name,Salary Reduction,Location
0,101,Rahul,3,25,0,45000,2,Pune,4,940000,540000,1,740000,Hyderabad
1,102,Priya,1,29,1,52000,4,Mumbai,5,1124000,624000,2,924000,Hyderabad
2,103,Amit,3,32,0,75000,8,Bengaluru,4,1300000,900000,3,1100000,Hyderabad
3,104,Sneha,4,28,1,60000,5,Pune,3,1020000,720000,4,820000,Hyderabad
4,105,Vikas,1,35,0,48000,6,Mumbai,4,976000,576000,5,776000,Hyderabad
5,106,Neha,3,27,1,65000,3,Bengaluru,5,1280000,780000,6,1080000,Hyderabad
6,107,Rohit,4,40,0,85000,12,Pune,3,1320000,1020000,7,1120000,Hyderabad
7,108,Pooja,3,30,1,70000,7,Mumbai,4,1240000,840000,8,1040000,Hyderabad
8,109,Karan,2,26,0,40000,1,Pune,3,780000,480000,9,680000,Hyderabad
9,110,Anjali,1,31,1,55000,5,Bengaluru,4,1060000,660000,10,860000,Hyderabad
10,111,Suresh,2,38,0,62000,9,Mumbai,5,1244000,744000,11,1044000,Hyderabad
11,112,Meera,4,33,1,72000,8,Pune,4,1264000,864000,12,1064000,Hyderabad
12,113,Akash,3,24,0,42000,1,Bengaluru,3,804000,504000,13,704000,Hyderabad
13,114,Riya,2,29,1,50000,3,Mumbai,4,1000000,600000,14,800000,Hyderabad
14,115,Nikhil,4,36,0,80000,10,Pune,5,1460000,960000,15,1260000,Hyderabad

In [54]:
# how to clean data 
# drop the column
# rename the column
# adding new column
# changing exist column
# creating the column using existing column

In [55]:
# to drop column
df2 = df.drop(["Gender" ,"Column name"] , axis = 1)
df2

,EmployeeID,Name,Department,Age,Salary,Experience,City,PerformanceRating,New Package,Old Package,Salary Reduction,Location
0,101,Rahul,3,25,45000,2,Pune,4,940000,540000,740000,Hyderabad
1,102,Priya,1,29,52000,4,Mumbai,5,1124000,624000,924000,Hyderabad
2,103,Amit,3,32,75000,8,Bengaluru,4,1300000,900000,1100000,Hyderabad
3,104,Sneha,4,28,60000,5,Pune,3,1020000,720000,820000,Hyderabad
4,105,Vikas,1,35,48000,6,Mumbai,4,976000,576000,776000,Hyderabad
5,106,Neha,3,27,65000,3,Bengaluru,5,1280000,780000,1080000,Hyderabad
6,107,Rohit,4,40,85000,12,Pune,3,1320000,1020000,1120000,Hyderabad
7,108,Pooja,3,30,70000,7,Mumbai,4,1240000,840000,1040000,Hyderabad
8,109,Karan,2,26,40000,1,Pune,3,780000,480000,680000,Hyderabad
9,110,Anjali,1,31,55000,5,Bengaluru,4,1060000,660000,860000,Hyderabad
10,111,Suresh,2,38,62000,9,Mumbai,5,1244000,744000,1044000,Hyderabad
11,112,Meera,4,33,72000,8,Pune,4,1264000,864000,1064000,Hyderabad
12,113,Akash,3,24,42000,1,Bengaluru,3,804000,504000,704000,Hyderabad
13,114,Riya,2,29,50000,3,Mumbai,4,1000000,600000,800000,Hyderabad
14,115,Nikhil,4,36,80000,10,Pune,5,1460000,960000,1260000,Hyderabad

In [56]:
df2.to_csv("Final Processed Dataframe.csv" , index = False)